namespace TestRender;

public enum TileType
{
    None = 0x00,                            // Kein Tile
    TallGrassWild = 0x02,                   // Hohes Gras (Wild)
    VeryTallGrassWild = 0x03,               // Sehr hohes Gras (Wild)
    TreeHeadbuttHGSS = 0x06,                // Baum (Kopfnuss in HGSS)
    CaveFloor = 0x08,                       // Höhlenboden
    OldChateauFloor = 0x0B,                 // Boden des Alten Anwesens
    GroundMountain = 0x0C,                  // Boden am Berg
    RiverWaterWild = 0x10,                  // Flusswasser (Wild)
    WhirlpoolHGSS = 0x11,                   // Strudel (HGSS)
    Waterfall = 0x13,                       // Wasserfall
    SeaWaterWild = 0x15,                    // Meerwasser (Wild)
    Puddle = 0x16,                          // Pfütze
    ShallowWalkableWater = 0x17,            // Flaches begehbares Wasser
    PuddleNoSplashing = 0x1D,               // Pfütze (kein Spritzen)
    Ice = 0x20,                             // Eis
    Sand = 0x21,                            // Sand
    CaveUnderwater = 0x22,                  // Unterwasser in Höhle
    SafariZoneBorder = 0x24,                // Grenze der Safari-Zone
    Magma = 0x2C,                           // Magma
    Reflection = 0x2D,                      // Reflexion
    BlockRight = 0x30,                      // Block (Rechts)
    BlockLeft = 0x31,                       // Block (Links)
    BlockUp = 0x32,                         // Block (Oben)
    BlockDown = 0x33,                       // Block (Unten)
    BlockRightUp = 0x34,                    // Block (Rechts & Oben)
    BlockLeftUp = 0x35,                     // Block (Links & Oben)
    BlockRightDown = 0x36,                  // Block (Rechts & Unten)
    BlockLeftDown = 0x37,                   // Block (Links & Unten)
    JumpRight = 0x38,                       // Sprung (Rechts)
    JumpLeft = 0x39,                        // Sprung (Links)
    JumpUpBrokenHGSS = 0x3A,                // Sprung (Oben, kaputt in HGSS)
    JumpDown = 0x3B,                        // Sprung (Unten)
    LadderFront = 0x3C,                     // Leiter (Vorderseite)
    LadderBack = 0x3D,                      // Leiter (Rückseite)
    LadderDown = 0x3E,                      // Leiter (Abwärts)
    JumpCornerDownLeft = 0x3F,              // Ecke Sprung (Unten Links)
    SlideRight = 0x40,                      // Rutsche (Rechts)
    SlideLeft = 0x41,                       // Rutsche (Links)
    SlideUp = 0x42,                         // Rutsche (Oben)
    SlideDown = 0x43,                       // Rutsche (Unten)
    BlockDownUp = 0x49,                     // Block (Unten & Oben)
    BlockLeftRight = 0x4A,                  // Block (Links & Rechts)
    VertRockClimb = 0x4B,                   // Vertikaler Felsenklettern
    HorizRockClimb = 0x4C,                  // Horizontaler Felsenklettern
    StopSliding = 0x4D,                     // Stoppen der Rutschbewegung
    JumpUpTwoTiles = 0x5A,                  // Sprung (Oben, zwei Kacheln)
    JumpDownTwoTiles = 0x5B,                // Sprung (Unten, zwei Kacheln)
    JumpLeftTwoTiles = 0x5C,                // Sprung (Links, zwei Kacheln)
    JumpRightTwoTiles = 0x5D,               // Sprung (Rechts, zwei Kacheln)
    StairsWarpRight = 0x5E,                 // Treppen Warp (Rechts)
    StairsWarpLeft = 0x5F,                  // Treppen Warp (Links)
    WarpEntranceRight = 0x62,               // Warp Eingang (Rechts)
    WarpEntranceLeft = 0x63,                // Warp Eingang (Links)
    WarpEntranceUp = 0x64,                  // Warp Eingang (Oben)
    WarpEntranceDown = 0x65,                // Warp Eingang (Unten)
    WarpPanel = 0x67,                       // Warp Panel
    DoorWarp = 0x69,                        // Tür Warp
    EscalatorWarpDownRight = 0x6A,           // Rolltreppe Warp (Abwärts-Rechts)
    EscalatorWarpUpRight = 0x6B,             // Rolltreppe Warp (Aufwärts-Rechts)
    WarpRight = 0x6C,                       // Warp (Rechts)
    WarpLeft = 0x6D,                        // Warp (Links)
    WarpUp = 0x6E,                          // Warp (Oben)
    WarpDown = 0x6F,                        // Warp (Unten)
    BridgeStart = 0x70,                     // Brückenbeginn
    BridgeMiddle = 0x71,                    // Brückenmitte
    BridgeOverCave = 0x72,                  // Brücke über Höhle
    BridgeOverWater = 0x73,                 // Brücke über Wasser
    BridgeOverSand = 0x74,                  // Brücke über Sand
    BridgeOverSnow = 0x75,                  // Brücke über Schnee
    VerticalBikeBridge = 0x76,              // Vertikale Fahrradbrücke
    VerticalBridgeGroundEncounters = 0x77,  // Vertikale Brücke (Bodenerfahrungen)
    VerticalBikeBridgeOverWater = 0x78,     // Vertikale Fahrradbrücke über Wasser
    VerticalBikeBridgeOverSand = 0x79,      // Vertikale Fahrradbrücke über Sand
    HorizontalBikeBridge = 0x7A,            // Horizontale Fahrradbrücke
    HorizontalBikeBridgeGroundEncounters = 0x7B, // Horizontale Fahrradbrücke (Bodenerfahrungen)
    HorizontalBikeBridgeOverWater = 0x7C,   // Horizontale Fahrradbrücke über Wasser
    HorizontalBikeBridgeOverSand = 0x7D,    // Horizontale Fahrradbrücke über Sand
    Table = 0x80,                           // Tisch
    StoragePC = 0x83,                       // Lager PC
    OpenTownMap = 0x85,                     // Offene Stadtkarte
    TV = 0x86,                              // Fernseher
    FarmLand = 0xA0,                        // Ackerland
    DeepSnow = 0xA1,                        // Tiefer Schnee
    VeryDeepSnow = 0xA2,                    // Sehr tiefer Schnee
    UltraDeepSnow = 0xA3,                   // Extrem tiefer Schnee
    Mud = 0xA4,                             // Schlamm
    DeepMud = 0xA5,                         // Tiefer Schlamm
    MudGrass1 = 0xA6,                       // Schlamm Gras 1
    MudGrass2 = 0xA7,                       // Schlamm Gras 2
    Snow = 0xA8,                            // Schnee
    SnowWithShadows = 0xA9,                 // Schnee mit Schatten
    BridgeHorizontal = 0xD5,                // Horizontale Brücke
    BikeJumpLeft = 0xD7,                    // Fahrrad Sprung (Links)
    BikeJumpRight = 0xD8,                   // Fahrrad Sprung (Rechts)
    BikeSlopeTop = 0xD9,                    // Fahrrad Steigung (Oben)
    BikeSlopeBottom = 0xDA,                 // Fahrrad Steigung (Unten)
    BikeParking = 0xDB,                     // Fahrradparken
    SmallBookshelf1 = 0xE0,                 // Kleines Bücherregal 1
    LargeBookshelf1 = 0xE1,                 // Großes Bücherregal 1
    LargeBookshelf2 = 0xE2,                 // Großes Bücherregal 2
    Pot = 0xE3,                             // Topf
    TrashCan = 0xE4,                        // Mülltonne
    StoreShelf1 = 0xE5,                     // Ladenregal 1
    Blueprint = 0xE6,                       // Bauplan
    SmallBookshelf2 = 0xEA,                 // Kleines Bücherregal 2
    StoreShelf2 = 0xEB,                     // Ladenregal 2
    StoreShelf3 = 0xEC,                     // Ladenregal 3
    NoAttribute = 0xFF,                     // Keine Eigenschaft
}